import type { Metadata } from "next";
import "./styles/globals.css";
import Navbar from "./UI/Navbar";
import { Toaster } from "@/app/UI/toaster"
import ProviderSession from "./lib/SessionProvider";


export const metadata: Metadata = {
  title: "Nestor news",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProviderSession>
          <Navbar />
          {children}
          <Toaster />
        </ProviderSession>
      </body>
    </html>
  );
}
