import type { Metadata } from "next";
import "./styles/globals.css";
import Navbar from "./UI/Navbar";


export const metadata: Metadata = {
  title: "Nestor news",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
